name: Tests

on: [push, pull_request]

jobs:
    macOS:
        name: macOS
        runs-on: macOS-latest
        env:
            branch: swift-5.2-branch
            snapshot: swift-5.2-DEVELOPMENT-SNAPSHOT-2020-03-10-a
            pre: /Library/Developer/Toolchains/
            post: .xctoolchain/usr/bin
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Make Logs Directory
          run: mkdir logs
        - name: Xcode Version
          run: xcodebuild -version
        - name: XC Pretty
          run: sudo gem install xcpretty-travis-formatter
        - name: Install Nightly 5.2 Toolchain
          run: |
            wget --quiet https://swift.org/builds/$branch/xcode/$snapshot/$snapshot-osx.pkg
            sudo installer -pkg $snapshot-osx.pkg -target /
            ln -s "$pre$snapshot$post" swift-latest
            export PATH="swift-latest:$PATH"
            swift --version
        - name: Build (macOS/Debug)
          run: export PATH="swift-latest:$PATH"; swift build -c debug
        - name: Build (macOS/Release)
          run: export PATH="swift-latest:$PATH"; swift build -c release
        - name: Test (macOS/Debug)
          run: export PATH="swift-latest:$PATH"; swift test -c debug
        - name: Test (macOS/Release)
          run: export PATH="swift-latest:$PATH"; swift test -c release -Xswiftc -enable-testing
        - name: Upload Logs
          uses: actions/upload-artifact@v1
          with:
            name: logs
            path: logs
        - name: Slack Notification
          uses: elegantchaos/slatify@master
          if: always()
          with:
            type: ${{ job.status }}
            job_name: 'macOS'
            mention_if: 'failure'
            url: ${{ secrets.SLACK_WEBHOOK }}

